require:
  - solidus_dev_support/rubocop

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - sandbox/**/*
    - spec/dummy/**/*
    - vendor/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: true
  Max: 190

RSpec/ExampleLength:
  Enabled: true
  Max: 20

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
