inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-i18n

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: true
  Max: 120

RSpec/ExampleLength:
  Enabled: true
  Max: 20

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
