inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-i18n

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
