version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1
  slack: circleci/slack@4.9.3

  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

commands:
  setup:
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install libvips
          command: |
            sudo apt-get update
            sudo apt-get install -yq libvips-dev

  test-branch:
    description:
      Runs tests for a specific Solidus branch.

    parameters:
      solidus_branch:
        type: string
      rails_version:
        type: string
      ruby_version:
        type: string
      database:
        type: string

    steps:
      - run:
          name: 'Solidus <<parameters.solidus_branch>>:  Install gems'
          command: |
            bundle install
          environment:
            RAILS_VERSION: <<parameters.rails_version>>
            SOLIDUS_BRANCH: <<parameters.solidus_branch>>
          when: always
      - run:
          name: 'Solidus <<parameters.solidus_branch>>:  Install sandbox with generated starter frontend'
          command: bin/sandbox --seed=false --sample=false
          environment:
            RAILS_ENV: development # if run in test mode will attempt to eager-load and break the sandbox
            RAILS_VERSION: <<parameters.rails_version>>
            SOLIDUS_BRANCH: <<parameters.solidus_branch>>
          when: always
      - run:
          name: 'Runs tests on Solidus <<parameters.solidus_branch>>'
          command: |
            cd sandbox
            bundle add rspec_junit_formatter --group test
            bundle exec rspec --format progress --format RspecJunitFormatter --out ../test-results/results.xml
          environment:
            RAILS_VERSION: <<parameters.rails_version>>
            SOLIDUS_BRANCH: <<parameters.solidus_branch>>
          when: always
      - run:
          command: rm -rf sandbox
          name: 'Solidus <<parameters.solidus_branch>>: Clean up'
          when: always

  notify:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: main, v[0-9]+\.[0-9]+

jobs:
  run-specs:
    executor:
        name: solidusio_extensions/<<parameters.database>>
        ruby_version: <<parameters.ruby_version>>
    steps:
      - setup
      - test-branch:
          solidus_branch: <<parameters.solidus_branch>>
          rails_version: <<parameters.rails_version>>
          ruby_version: <<parameters.ruby_version>>
          database: <<parameters.database>>
      - solidusio_extensions/store-test-results
      - notify
    parameters:
      solidus_branch:
        type: string
        default: 'master'
      rails_version:
        type: string
        default: '~> 7.0'
      ruby_version:
        type: string
      database:
        type: string

workflows:
  "Run specs on development Solidus version":
    jobs:
      - run-specs:
          context: slack-secrets
          name: run-specs-with-postgres-ruby-3-2
          database: 'postgres'
          ruby_version: '3.2'

      - run-specs:
          context: slack-secrets
          name: run-specs-with-postgres-ruby-3-1
          database: 'postgres'
          ruby_version: '3.1'

      - run-specs:
          context: slack-secrets
          name: run-specs-with-postgres-ruby-3-0
          database: 'postgres'
          ruby_version: '2.7'

      - run-specs:
          context: slack-secrets
          name: run-specs-with-mysql-ruby-3-2
          database: 'mysql'
          ruby_version: '3.2'

      - run-specs:
          context: slack-secrets
          name: run-specs-with-sqlite-ruby-3-2
          database: 'sqlite'
          ruby_version: '3.2'
