version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

jobs:
  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
  solidus-compare:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Prepare compare diff
          command: bin/solidus_compare > /tmp/solidus_compare_results.diff
      - store_artifacts:
          path: /tmp/solidus_compare_results.diff
          destination: solidus_compare_results.diff
      - run:
          name: Prepare test results
          command: mkdir -p /tmp/test_results && bin/solidus_compare -s > /tmp/test_results/results.xml
      - store_test_results:
          path: /tmp/test_results

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
      - solidus-compare
  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
      - solidus-compare
