version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0

  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

commands:
  setup:
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Install libvips
          command: sudo apt-get install -y libvips

  test-branch:
    description:
      Runs tests for a specific Solidus branch.

    parameters:
      branch:
        type: string
        default: master
      command:
        type: string
        default: |
          cd sandbox
          bundle add rspec_junit_formatter --group test
          bundle exec rspec --format progress --format RspecJunitFormatter --out $TEST_RESULTS_PATH
      command_verb:
        type: string
        default: Runs tests
      rails_version:
        type: string

    steps:
      - run:
          name: 'Solidus <<parameters.branch>>:  Install gems'
          command: |
            bundle config --local path vendor/bundle/<<parameters.branch>>
            bundle install
            bundle clean
          environment:
            RAILS_VERSION: <<parameters.rails_version>>
            SOLIDUS_BRANCH: <<parameters.branch>>
          when: always
      - run:
          name: 'Solidus <<parameters.branch>>:  Install sandbox with generated starter frontend'
          command: bin/sandbox --seed=false --sample=false
          environment:
            RAILS_VERSION: <<parameters.rails_version>>
            SANDBOX_BUNDLE_PATH: ../vendor/bundle/<<parameters.branch>>
            SOLIDUS_BRANCH: <<parameters.branch>>
          when: always
      - run:
          name: '<<parameters.command_verb>> on Solidus <<parameters.branch>>'
          command: <<parameters.command>>
          environment:
            RAILS_VERSION: <<parameters.rails_version>>
            SOLIDUS_BRANCH: <<parameters.branch>>
            TEST_RESULTS_PATH: ../test-results/gems-v3-ruby-v2-7-solidus-<<parameters.branch>>/results.xml
          when: always
      - run:
          command: rm -rf sandbox
          name: 'Solidus <<parameters.branch>>: Clean up'
          when: always

jobs:
  run-specs:
    executor:
        name: solidusio_extensions/<<parameters.database>>
        ruby_version: <<parameters.ruby_version>>
    steps:
      - setup
      - test-branch:
          branch: <<parameters.solidus_branch>>
          rails_version: <<parameters.rails_version>>
      - solidusio_extensions/store-test-results
    parameters:
      solidus_branch:
        type: string
        default: 'v3.2'
      rails_version:
        type: string
        default: '~> 7.0'
      ruby_version:
        type: string
        default: '3.1'
      database:
        type: string
        default: 'postgres'

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs:
          name: run-specs-with-postgres
          database: 'postgres'
          ruby_version: '2.7'
          solidus_branch: 'v3.1'
          rails_version: '~> 6.1'

      - run-specs:
          name: run-specs-with-mysql
          database: 'mysql'
          ruby_version: '3.0'
          solidus_branch: 'v3.1'
          rails_version: '~> 6.1'

      - run-specs:
          name: run-specs-with-postgres-and-solidus-latest
          database: 'postgres'
          ruby_version: '3.0'
          solidus_branch: 'master'
          rails_version: '~> 7.0'

      - run-specs:
          name: run-specs-with-mysql-and-solidus-latest
          database: 'mysql'
          ruby_version: '3.1'
          solidus_branch: 'master'
          rails_version: '~> 7.0'

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs:
          name: run-specs-with-postgres
          database: 'postgres'
          ruby_version: '2.7'
          solidus_branch: 'v3.1'
          rails_version: '~> 6.1'

      - run-specs:
          name: run-specs-with-mysql
          database: 'mysql'
          ruby_version: '3.0'
          solidus_branch: 'v3.1'
          rails_version: '~> 6.1'

      - run-specs:
          name: run-specs-with-postgres-and-solidus-latest
          database: 'postgres'
          ruby_version: '3.0'
          solidus_branch: 'master'
          rails_version: '~> 7.0'

      - run-specs:
          name: run-specs-with-mysql-and-solidus-latest
          database: 'mysql'
          ruby_version: '3.1'
          solidus_branch: 'master'
          rails_version: '~> 7.0'
