---
project_paths:
- app/controllers
- app/helpers
project_branch: master
source_repo: https://github.com/solidusio/solidus.git
source_name: solidus
source_branch: master
source_base_path: frontend/
ignore:
- path: app/controllers
  diffs:
  - hash: 3804005517
    file: concerns/solidus_starter_frontend/auth_views.rb
  - hash: 3208037425
    file: concerns/solidus_starter_frontend/taxonomies.rb
